### PR TITLE
- Added documentation

### PR DESCRIPTION
**Pull request by alexsporn**

### CODE REVIEW

**Review by muXxer — APPROVED** [review]

**Review by Dr-Electron — COMMENTED** [review]
LGTM. But you can delete the yarn-3.2.0.cjs file

**Comment by alexsporn** [comment]
> LGTM. But you can delete the yarn-3.2.0.cjs file

but you did not tell me to remove it from inx-indexer

**Comment by alexsporn** [comment]
Sorry, had a brain fart and merged it before deleting the file

**Comment by Dr-Electron** [comment]
> > LGTM. But you can delete the yarn-3.2.0.cjs file
> 
> but you did not tell me to remove it from inx-indexer

Are you sure?
https://github.com/iotaledger/inx-indexer/pull/45#discussion_r926605854 :trollface: 

`You can remove the .yarn folder now as we use the new core pack enable to make sure the correct version of yarn is used`

**Comment by alexsporn** [comment]
A comment under a code change proposal. Who reads those anyway :trollface:

I removed the folder from this repo and the indexer now. Thanks

**Pull request merged**
